version: '2.1'
services:

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5433:5432"
  
  redis:
    image: redis:5.0.3
    ports:
      - 6379:6379

  airflow:
    build: .
    restart: always
    container_name: airflow
    volumes:
      - ./airflow.cfg:/opt/airflow/airflow.cfg
      - ../dags:/opt/airflow/dags
    ports:
      - 8080:8080
    env_file:
      - ../.env
    healthcheck:
      test: [ "CMD", "nc", "-z", "airflow", "8080" ]
      timeout: 45s
      interval: 10s
      retries: 10
